### ISSUE TITLE
好像没办法支持lumen

### ISSUE THREAD

**Issue by dishcheng** [y-ui/laravel-running-time#4]
能想办法支持下lumen吗？

**Comment by y-ui** [comment]
好，我先调研一下能不能快速支持

**Comment by y-ui** [comment]
由于我开发的时候没有考虑到LUMEN，修改起来很费时，放弃LUMEN了

**Comment by dishcheng** [comment]
https://github.com/dishcheng/lumen-runningTime

**Comment by dishcheng** [comment]
改写了一下，好像还可以，我主要只改了你的中间件，https://github.com/dishcheng/lumen-runningTime
